# Generated by Django 2.1 on 2018-08-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
    ]
