# Generated by Django 2.1 on 2018-08-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristsapp', '0004_auto_20180828_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='touristsapp.Location'),
        ),
    ]
